apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: prometheus-config
  namespace: monitoring
data:
  prometheus.yaml: |
    global:
      scrape_interval: 15s
    scrape_configs:
    - job_name: prometheus
      scrape_interval: 3s
      static_configs:
      - targets:
        - localhost:9090
    - job_name: gpu_cpu_metrics
      scrape_interval: 3s
      metrics_path: /metrics
      scheme: http
      static_configs:
      - targets:
        - localhost:9100
